### ISSUE TITLE
Issues running docker composer build

### ISSUE THREAD

**Issue by davidlindgren** [amborle/featmap#78]
Hello there, Featmap authors!

Hope this message finds you well. Congratulations on creating this tool and making it available.
If I may ask, I'm going through some issues I'm not being able to resolve myself, thus I'd like to see if you can provide some guidance.

I found 3 issues so far, 1 of which I think I solved. These are:

**1. go-bindata**

```
 => ERROR [ 4/11] RUN go get -u github.com/jteeuwen/go-bindata/...                                  0.5s
------                                                                                                   
 > [ 4/11] RUN go get -u github.com/jteeuwen/go-bindata/...:                                             
#0 0.303 go: go.mod file not found in current directory or any parent directory.                         
#0 0.303        'go get' is no longer supported outside a module.                                        
#0 0.303        To build and install a command, use 'go install' with a version,                         
#0 0.303        like 'go install example.com/cmd@latest'                                                 
#0 0.303 	For more information, see https://golang.org/doc/go-get-install-deprecation
#0 0.303 	or run 'go help get' or 'go help install'.
```

This one I fixed by replacing the command, and making it use 'go install' instead.

**2. Next, I got a dependency issue with the history module:**

 ```
=> ERROR [ 6/11] RUN cd ./webapp &&     npm install                                                8.8s
------                                                                                                   
 > [ 6/11] RUN cd ./webapp &&     npm install:
#0 8.775 npm ERR! code ERESOLVE
#0 8.779 npm ERR! ERESOLVE unable to resolve dependency tree
#0 8.779 npm ERR! 
#0 8.779 npm ERR! While resolving: featmap-client@0.1.0
#0 8.780 npm ERR! Found: history@5.3.0
#0 8.780 npm ERR! node_modules/history
#0 8.780 npm ERR!   history@"^5.0.0" from the root project
#0 8.780 npm ERR! 
#0 8.780 npm ERR! Could not resolve dependency:
#0 8.780 npm ERR! peer history@"^4.7.2" from connected-react-router@6.9.3
#0 8.780 npm ERR! node_modules/connected-react-router
#0 8.780 npm ERR!   connected-react-router@"^6.9.1" from the root project
#0 8.780 npm ERR! 
#0 8.780 npm ERR! Fix the upstream dependency conflict, or retry
#0 8.781 npm ERR! this command with --force or --legacy-peer-deps
#0 8.781 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
#0 8.781 npm ERR! 
#0 8.781 npm ERR! 
#0 8.781 npm ERR! For a full report see:
#0 8.781 npm ERR! /root/.npm/_logs/2023-04-07T01_54_26_710Z-eresolve-report.txt
#0 8.784 
#0 8.784 npm ERR! A complete log of this run can be found in:
#0 8.784 npm ERR!     /root/.npm/_logs/2023-04-07T01_54_26_710Z-debug-0.log

```
Couldn't manage to resolve it properly, but in an attempt to move forward, used the --force parameter as suggested

**3. Then, got to this SSL related issue, which may have something to do with Node version being used in build process**

```
=> ERROR [ 8/11] RUN cd ./webapp &&     npm run build                                              6.5s 
------                                                                                                   
 > [ 8/11] RUN cd ./webapp &&     npm run build:                                                         
#0 0.968                                                                                                 
#0 0.968 > featmap-client@0.1.0 build                                                                    
#0 0.968 > react-scripts build                                                                           
#0 0.968                                                                                                 
#0 4.120 Creating an optimized production build...
#0 5.626 Error: error:0308010C:digital envelope routines::unsupported
#0 5.626     at new Hash (node:internal/crypto/hash:71:19)
#0 5.626     at Object.createHash (node:crypto:140:10)
#0 5.626     at module.exports (/src/webapp/node_modules/webpack/lib/util/createHash.js:135:53)
#0 5.626     at NormalModule._initBuildHash (/src/webapp/node_modules/webpack/lib/NormalModule.js:417:16)
#0 5.626     at handleParseError (/src/webapp/node_modules/webpack/lib/NormalModule.js:471:10)
#0 5.626     at /src/webapp/node_modules/webpack/lib/NormalModule.js:503:5
#0 5.626     at /src/webapp/node_modules/webpack/lib/NormalModule.js:358:12
#0 5.626     at /src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:373:3
#0 5.626     at iterateNormalLoaders (/src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
#0 5.626     at iterateNormalLoaders (/src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
#0 5.626     at /src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:236:3
#0 5.626     at runSyncOrAsync (/src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
#0 5.626     at iterateNormalLoaders (/src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
#0 5.626     at Array.<anonymous> (/src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
#0 5.626     at Storage.finished (/src/webapp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
#0 5.626     at /src/webapp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
#0 5.672 /src/webapp/node_modules/react-scripts/scripts/build.js:19
#0 5.672   throw err;
#0 5.672   ^
#0 5.672 
#0 5.672 Error: error:0308010C:digital envelope routines::unsupported
#0 5.672     at new Hash (node:internal/crypto/hash:71:19)
#0 5.672     at Object.createHash (node:crypto:140:10)
#0 5.672     at module.exports (/src/webapp/node_modules/webpack/lib/util/createHash.js:135:53)
#0 5.672     at NormalModule._initBuildHash (/src/webapp/node_modules/webpack/lib/NormalModule.js:417:16)
#0 5.672     at /src/webapp/node_modules/webpack/lib/NormalModule.js:452:10
#0 5.672     at /src/webapp/node_modules/webpack/lib/NormalModule.js:323:13
#0 5.672     at /src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:367:11
#0 5.672     at /src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:233:18
#0 5.672     at context.callback (/src/webapp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
#0 5.672     at /src/webapp/node_modules/babel-loader/lib/index.js:59:103 {
#0 5.672   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
#0 5.672   library: 'digital envelope routines',
#0 5.672   reason: 'unsupported',
#0 5.672   code: 'ERR_OSSL_EVP_UNSUPPORTED'
#0 5.672 }
#0 5.672 
#0 5.672 Node.js v19.7.0
```

This one I really didn't manage to overcome.

Can you please have a look at these and provide some help?

Much appreciated.

KR,

David

_Originally posted by @davidlindgren in https://github.com/amborle/featmap/discussions/77_

**Comment by amborle** [comment]
This has been fixed.
